name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: nicolaschan/wispy@v2
        with:
          server-url: ${{ vars.WISPY_SERVER_URL }}
          token:      ${{ secrets.WISPY_TOKEN }}
      - run: nix build
